In [1]:
import p1
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np


image = Image.open('img.jpg')
image_np = np.array(image)
# print(image_np)

x = 2/3.0
print(x)
# image_float = image_np.astype(np.float32)/255.0

# plt.imshow(image_float)

0.6666666666666666


In [1]:
print(image_np)

NameError: name 'image_np' is not defined

In [4]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
np.pad(a, ((1, 1), (11, 11)) , 'constant', constant_values=(0, 11))

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 12, 13, 14, 15,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 11, 11, 11, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11]])

In [5]:
# np.pad(image_float, [(2, 2), (3, 3)], 'constant', constant_values = (0)).shape


In [10]:
c_image = np.zeros((3, 2, 3))
print(c_image[-1:3])

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [27]:
c1_image = np.zeros(2)
print(c1_image)

[0. 0.]


In [41]:
print(a[0:3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [7]:
for i in range(5):
    print(i)

0
1
2
3
4


In [3]:
filt_2 = np.array([[0.5, 0, -0.5]])
print(filt_2)

[[ 0.5  0.  -0.5]]


In [5]:
x = np.arange(10)
print(x < 5)

[ True  True  True  True  True False False False False False]


In [23]:
def check_distance_from_line(x, y, theta, c, thresh):

    dist = np.abs((x * np.cos(theta)) + (y * np.sin(theta)) + c)
    
    return dist

In [22]:
theta = -1.57079633
c = 274.89321881 
x = np.array([10,100,300,0,100,100,100])
y = np.array([275,275,275,0,100,274,276])

for xs in range(500):
    for ys in range(500):
        dist = check_distance_from_line(xs, ys, theta, c, 0.3)


        if (dist < 0.3):
            print(xs, ys)


0 275
1 275
2 275
3 275
4 275
5 275
6 275
7 275
8 275
9 275
10 275
11 275
12 275
13 275
14 275
15 275
16 275
17 275
18 275
19 275
20 275
21 275
22 275
23 275
24 275
25 275
26 275
27 275
28 275
29 275
30 275
31 275
32 275
33 275
34 275
35 275
36 275
37 275
38 275
39 275
40 275
41 275
42 275
43 275
44 275
45 275
46 275
47 275
48 275
49 275
50 275
51 275
52 275
53 275
54 275
55 275
56 275
57 275
58 275
59 275
60 275
61 275
62 275
63 275
64 275
65 275
66 275
67 275
68 275
69 275
70 275
71 275
72 275
73 275
74 275
75 275
76 275
77 275
78 275
79 275
80 275
81 275
82 275
83 275
84 275
85 275
86 275
87 275
88 275
89 275
90 275
91 275
92 275
93 275
94 275
95 275
96 275
97 275
98 275
99 275
100 275
101 275
102 275
103 275
104 275
105 275
106 275
107 275
108 275
109 275
110 275
111 275
112 275
113 275
114 275
115 275
116 275
117 275
118 275
119 275
120 275
121 275
122 275
123 275
124 275
125 275
126 275
127 275
128 275
129 275
130 275
131 275
132 275
133 275
134 275
135 275
136 275
137 275
138 27